[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "TrioMix"
authors = [{name = "Christopher Jongsoo Yoon", email = "cjyoon@wustl.edu"}]
dynamic = ["version", "description"]
